config/routes.rb
Verbapp::Application.routes.draw do
  get "verbosirregulares/verbos_irregulares_ar"
  get "verbosirregulares/verbos_irregulares_er"
  get "verbosirregulares/verbos_irregulares_ir"
  get "verbosirregulares/verbosauxiliares"

  get "verbosregulares/verbos_regulares_ar"
  get "verbosregulares/verbos_regulares_er"
  get "verbosregulares/verbos_regulares_ir"

  get "irregularverbs/index"
  get "verbosregulares/verbos_irregulares_er"
  get "irregularverbs/conjugacao_verbos_ar"

  resources :verbs
  resources :irregularverbs

  root :to => 'home#index'

end

app/models/verb.rb
class Verb < ActiveRecord::Base
  attr_accessible :cond_ele, :cond_eles, :cond_eu, :cond_nos, :definition, :entry_id, :fut_ele, :fut_eles, :fut_eu, :fut_nos, :fut_sub_ele, :fut_sub_eles, :fut_sub_eu, :fut_sub_nos, :gerundio, :imp_ele, :imp_eles, :imp_eu, :imp_nos, :imp_sub_ele, :imp_sub_eles, :imp_sub_eu, :imp_sub_nos, :participio, :pres_ele, :pres_eles, :pres_eu, :pres_nos, :pres_sub_ele, :pres_sub_eles, :pres_sub_eu, :pres_sub_nos, :pret_ele, :pret_eles, :pret_eu, :pret_nos, :sent1, :sent2, :sent3, :sent4, :verb
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/irregularverbs_controller.rb
class IrregularverbsController < ApplicationController
  # GET /verbs
  # GET /verbs.json
  def index
    @verbs = Verb.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @verbs }
    end
  end

  # GET /verbs/1
  # GET /verbs/1.json
  def show
    @verb = Verb.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @verb }
    end
  end

  # GET /verbs/new
  # GET /verbs/new.json
  def new
    @verb = Verb.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @verb }
    end
  end

  # GET /verbs/1/edit
  def edit
    @verb = Verb.find(params[:id])
  end

  # POST /verbs
  # POST /verbs.json
  def create
    @verb = Verb.new(params[:verb])

    respond_to do |format|
      if @verb.save
        format.html { redirect_to @verb, notice: 'Verb was successfully created.' }
        format.json { render json: @verb, status: :created, location: @verb }
      else
        format.html { render action: "new" }
        format.json { render json: @verb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /verbs/1
  # PUT /verbs/1.json
  def update
    @verb = Verb.find(params[:id])

    respond_to do |format|
      if @verb.update_attributes(params[:verb])
        format.html { redirect_to @verb, notice: 'Verb was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @verb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verbs/1
  # DELETE /verbs/1.json
  def destroy
    @verb = Verb.find(params[:id])
    @verb.destroy

    respond_to do |format|
      format.html { redirect_to verbs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/verbosirregulares_controller.rb
class VerbosirregularesController < ApplicationController
  def verbos_irregulares_er
  end
end

app/controllers/verbosregulares_controller.rb
class VerbosregularesController < ApplicationController
  def verbos_regulares_ar
  end
end

app/controllers/verbs_controller.rb
class VerbsController < ApplicationController
  # GET /verbs
  # GET /verbs.json
  def index
    @verbs = Verb.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @verbs }
    end
  end

  # GET /verbs/1
  # GET /verbs/1.json
  def show
    @verb = Verb.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @verb }
    end
  end

  # GET /verbs/new
  # GET /verbs/new.json
  def new
    @verb = Verb.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @verb }
    end
  end

  # GET /verbs/1/edit
  def edit
    @verb = Verb.find(params[:id])
  end

  # POST /verbs
  # POST /verbs.json
  def create
    @verb = Verb.new(params[:verb])

    respond_to do |format|
      if @verb.save
        format.html { redirect_to @verb, notice: 'Verb was successfully created.' }
        format.json { render json: @verb, status: :created, location: @verb }
      else
        format.html { render action: "new" }
        format.json { render json: @verb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /verbs/1
  # PUT /verbs/1.json
  def update
    @verb = Verb.find(params[:id])

    respond_to do |format|
      if @verb.update_attributes(params[:verb])
        format.html { redirect_to @verb, notice: 'Verb was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @verb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verbs/1
  # DELETE /verbs/1.json
  def destroy
    @verb = Verb.find(params[:id])
    @verb.destroy

    respond_to do |format|
      format.html { redirect_to verbs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/irregularverbs_helper.rb
module IrregularverbsHelper
end

app/helpers/verbosirregulares_helper.rb
module VerbosirregularesHelper
end

app/helpers/verbosregulares_helper.rb
module VerbosregularesHelper
end

app/helpers/verbs_helper.rb
module VerbsHelper
end

app/views/greetings/goodbye.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>

<head>

  <title>Brasil Home Page</title>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>


  <script type="text/javascript">

      $(document).ready(function () {

          $.ajax({
              type: "GET",
              url: "/andrew.xml",
              dataType: "xml",

              success: function (xml) {
                  var select = $('#mySelect');

                  $(xml).find('product').each(function () {
                      var title = $(this).attr('Verb');
                      var value = $(this).attr('EntryID');
                      select.append("<option value='" + value + "'>" + title + "</option>");
                  });

                  select.children(":first").attr("selected", true);
              }

          });

          $("#quote").load("/start_page.htm");

          $("#mySelect").change(function () {
              if ($('#mySelect').val() == "verbs") {
                  $("#quote").load("/start_page.htm");
              }
              if ($('#mySelect').val() != "verbs") {
                  $("#quote").load("/verbs/" + $('#mySelect').val());
              }
          });

      });

  </script>

  <style type="text/css" class="style3">
      <!--
      .style3 {
          border: 1px none #ff0000;
          color: #000000;
          font-family: Georgia, "Times New Roman", Times, serif;
          font-size: 18pt;
          overflow: hidden;
          width: 200px;
      }

      -->
  </style>

</head>

<body bgcolor="#ffffff">

<div style="position:absolute; width: 220px; height: 40px; z-index:1; left: 48px; top: 0px;
        vertical-align: text-top; border: 1px solid #000000; font-family: arial;" class="style3">
  <br>Conjagação verbal
</div>

<div style="position:absolute; width: 560px; height: 40px; z-index:1; left: 800px; top: 0px;
        vertical-align: text-top; border: 1px solid #000000; font-family: arial;" class="style3">
  <script language="JavaScript1.2">
      var months = new Array(13);
      months [1] = "janeiro";
      months [2] = "fevereiro";
      months [3] = "março";
      months [4] = "abril";
      months [5] = "maio";
      months [6] = "junho";
      months [7] = "julho";
      months [8] = "agosto";
      months [9] = "setembro";
      months [10] = "outubro";
      months [11] = "novembro";
      months [12] = "dezembro";
      var dayName = new Array(7);
      dayName [0] = "domingo";
      dayName [1] = "segunda-feira";
      dayName [2] = "terça-feira";
      dayName [3] = "quarta-feira";
      dayName [4] = "quinta-feira";
      dayName [5] = "sexta-feira";
      dayName [6] = "sábado";
      var time = new Date();
      var lmonth = months[time.getMonth() + 1];
      var lday = dayName[time.getDay()];
      var date = time.getDate();
      var year = time.getYear();
      if (year < 2000) {
          year = year + 1900;
      }
      document.write("<br>hoje é " + lday + " " + date + " de " + lmonth + " de " + year);
  </script>
</div>

<div id="quote" style="z-index:0; position:absolute; left: 200px; top: 50px; background-color: #ffffff;
        layer-background-color: #00FF00; border: 1px solid #000000; width: 1140px; height: 540px;"></div>

<div style="z-index:1; position: absolute; width: 137px; height: 540px; left: 48px; top: 50px; border: 1px solid #000000;">
  <div id="andrew1">
    <form>
      <select size="25" id="mySelect">
        <option value="verbs">Escolha um verbo</option>
      </select>
    </form>
  </div>
</div>

</body>

</html>

app/views/home/index.html.erb
<div id="bandeiranacional" 
  style="position: absolute; width: 500px; height: 800px; z-index: -1; left: 0px; top: 0px">
</div>
<div id="american_flag" 
  style="position: absolute; width: 500px; height: 800px; z-index: -1; left: 1155px; top: 0px">
</div>

<div id="title" 
  style="position: absolute; width: 850px; height: 30px; left: 230px; top: 10px; font-family: Arial, Helvetica, sans-serif; color: #000080; font-size: xx-large; text-align: center; border: 1px none #ff0000;">
  Conjugador de Verbos da Língua Portuguesa by Andrew (a simple test))</div>
<div id="signature" 
  style="position: absolute; width: 850px; height: 20px; left: 230px; top: 50px; font-family: Arial, Helvetica, sans-serif; color: #000000; font-size: small; text-align: center; font-style: italic;">
  a portuguese verb conjugator created using Ruby on Rails</div>
<div id="verbos_regulares_ar" 
  style="position: absolute; width: 850px; height: 20px; left: 230px; top: 90px; font-family: Arial, Helvetica, sans-serif; font-size: medium; text-align: center">
  <%= link_to "verbos regulares comuns da primeira conjugação (-ar)", 'verbosregulares/verbos_regulares_ar' %>
</div>
<div id="verbos_regulares_er" 
  style="position: absolute; width: 850px; height: 20px; left: 230px; top: 140px; font-family: Arial, Helvetica, sans-serif; font-size: medium; text-align: center">
  <%= link_to "verbos regulares comuns da segunda conjugação (-er)", 'verbosregulares/verbos_regulares_er' %>
</div>
<div id="verbos_regulares_ir" 
  style="position: absolute; width: 850px; height: 20px; left: 230px; top: 190px; font-family: Arial, Helvetica, sans-serif; font-size: medium; text-align: center">
  <%= link_to "verbos regulares comuns da terceira conjugação (-ir)", 'verbosregulares/verbos_regulares_ir' %>
</div>
<div id="verbos_irregulares_ar" 
  style="position: absolute; width: 850px; height: 20px; left: 230px; top: 240px; font-family: Arial, Helvetica, sans-serif; font-size: medium; text-align: center">
  <%= link_to "verbos irregulares comuns da primeira conjugação (-ar)", 'verbosirregulares/verbos_irregulares_ar' %>
</div>
<div id="verbos_irregulares_er" 
  style="position: absolute; width: 850px; height: 20px; left: 230px; top: 290px; font-family: Arial, Helvetica, sans-serif; font-size: medium; text-align: center">
  <%= link_to "verbos irregulares comuns da segunda conjugação (-er)", 'verbosirregulares/verbos_irregulares_er' %>
</div>
<div id="verbos_irregulares_ir" 
  style="position: absolute; width: 850px; height: 20px; left: 230px; top: 340px; font-family: Arial, Helvetica, sans-serif; font-size: medium; text-align: center">
  <%= link_to "verbos irregulares comuns da terceira conjugação (-ir)", 'verbosirregulares/verbos_irregulares_ir' %>
</div>

app/views/irregularverbs/_form.html.erb
<%= form_for(@verb) do |f| %>
    <% if @verb.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@verb.errors.count, "error") %> prohibited this verb from being saved:</h2>

          <ul>
            <% @verb.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :verb %>
      <br/>
      <%= f.text_area :verb %>
    </div>
    <div class="field">
      <%= f.label :entry_id %>
      <br/>
      <%= f.text_area :entry_id %>
    </div>
    <div class="field">
      <%= f.label :definition %>
      <br/>
      <%= f.text_area :definition %>
    </div>
    <div class="field">
      <%= f.label :gerundio %>
      <br/>
      <%= f.text_area :gerundio %>
    </div>
    <div class="field">
      <%= f.label :participio %>
      <br/>
      <%= f.text_area :participio %>
    </div>
    <div class="field">
      <%= f.label :pres_eu %>
      <br/>
      <%= f.text_area :pres_eu %>
    </div>
    <div class="field">
      <%= f.label :pres_ele %>
      <br/>
      <%= f.text_area :pres_ele %>
    </div>
    <div class="field">
      <%= f.label :pres_nos %>
      <br/>
      <%= f.text_area :pres_nos %>
    </div>
    <div class="field">
      <%= f.label :pres_eles %>
      <br/>
      <%= f.text_area :pres_eles %>
    </div>
    <div class="field">
      <%= f.label :pret_eu %>
      <br/>
      <%= f.text_area :pret_eu %>
    </div>
    <div class="field">
      <%= f.label :pret_ele %>
      <br/>
      <%= f.text_area :pret_ele %>
    </div>
    <div class="field">
      <%= f.label :pret_nos %>
      <br/>
      <%= f.text_area :pret_nos %>
    </div>
    <div class="field">
      <%= f.label :pret_eles %>
      <br/>
      <%= f.text_area :pret_eles %>
    </div>
    <div class="field">
      <%= f.label :imp_eu %>
      <br/>
      <%= f.text_area :imp_eu %>
    </div>
    <div class="field">
      <%= f.label :imp_ele %>
      <br/>
      <%= f.text_area :imp_ele %>
    </div>
    <div class="field">
      <%= f.label :imp_nos %>
      <br/>
      <%= f.text_area :imp_nos %>
    </div>
    <div class="field">
      <%= f.label :imp_eles %>
      <br/>
      <%= f.text_area :imp_eles %>
    </div>
    <div class="field">
      <%= f.label :fut_eu %>
      <br/>
      <%= f.text_area :fut_eu %>
    </div>
    <div class="field">
      <%= f.label :fut_ele %>
      <br/>
      <%= f.text_area :fut_ele %>
    </div>
    <div class="field">
      <%= f.label :fut_nos %>
      <br/>
      <%= f.text_area :fut_nos %>
    </div>
    <div class="field">
      <%= f.label :fut_eles %>
      <br/>
      <%= f.text_area :fut_eles %>
    </div>
    <div class="field">
      <%= f.label :cond_eu %>
      <br/>
      <%= f.text_area :cond_eu %>
    </div>
    <div class="field">
      <%= f.label :cond_ele %>
      <br/>
      <%= f.text_area :cond_ele %>
    </div>
    <div class="field">
      <%= f.label :cond_nos %>
      <br/>
      <%= f.text_area :cond_nos %>
    </div>
    <div class="field">
      <%= f.label :cond_eles %>
      <br/>
      <%= f.text_area :cond_eles %>
    </div>
    <div class="field">
      <%= f.label :pres_sub_eu %>
      <br/>
      <%= f.text_area :pres_sub_eu %>
    </div>
    <div class="field">
      <%= f.label :pres_sub_ele %>
      <br/>
      <%= f.text_area :pres_sub_ele %>
    </div>
    <div class="field">
      <%= f.label :pres_sub_nos %>
      <br/>
      <%= f.text_area :pres_sub_nos %>
    </div>
    <div class="field">
      <%= f.label :pres_sub_eles %>
      <br/>
      <%= f.text_area :pres_sub_eles %>
    </div>
    <div class="field">
      <%= f.label :imp_sub_eu %>
      <br/>
      <%= f.text_area :imp_sub_eu %>
    </div>
    <div class="field">
      <%= f.label :imp_sub_ele %>
      <br/>
      <%= f.text_area :imp_sub_ele %>
    </div>
    <div class="field">
      <%= f.label :imp_sub_nos %>
      <br/>
      <%= f.text_area :imp_sub_nos %>
    </div>
    <div class="field">
      <%= f.label :imp_sub_eles %>
      <br/>
      <%= f.text_area :imp_sub_eles %>
    </div>
    <div class="field">
      <%= f.label :fut_sub_eu %>
      <br/>
      <%= f.text_area :fut_sub_eu %>
    </div>
    <div class="field">
      <%= f.label :fut_sub_ele %>
      <br/>
      <%= f.text_area :fut_sub_ele %>
    </div>
    <div class="field">
      <%= f.label :fut_sub_nos %>
      <br/>
      <%= f.text_area :fut_sub_nos %>
    </div>
    <div class="field">
      <%= f.label :fut_sub_eles %>
      <br/>
      <%= f.text_area :fut_sub_eles %>
    </div>
    <div class="field">
      <%= f.label :sent1 %>
      <br/>
      <%= f.text_area :sent1 %>
    </div>
    <div class="field">
      <%= f.label :sent2 %>
      <br/>
      <%= f.text_area :sent2 %>
    </div>
    <div class="field">
      <%= f.label :sent3 %>
      <br/>
      <%= f.text_area :sent3 %>
    </div>
    <div class="field">
      <%= f.label :sent4 %>
      <br/>
      <%= f.text_area :sent4 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/irregularverbs/edit.html.erb
<h1>Editing verb</h1>

<%= render 'form' %>

<%= link_to 'Show', @verb %> |
<%= link_to 'Back', verbs_path %>

app/views/irregularverbs/index.html.erb
<h1>Listing verbs</h1>

<table>
  <tr>
    <th>Entry</th>
    <th>Verb</th>
    <th>Definition</th>
    <th>Gerundio</th>
    <th>Participio</th>
    <th>Pres eu</th>
    <th>Pres ele</th>
    <th>Pres nos</th>
    <th>Pres eles</th>
    <th>Pret eu</th>
    <th>Pret ele</th>
    <th>Pret nos</th>
    <th>Pret eles</th>
    <th>Imp eu</th>
    <th>Imp ele</th>
    <th>Imp nos</th>
    <th>Imp eles</th>
    <th>Fut eu</th>
    <th>Fut ele</th>
    <th>Fut nos</th>
    <th>Fut eles</th>
    <th>Cond eu</th>
    <th>Cond ele</th>
    <th>Cond nos</th>
    <th>Cond eles</th>
    <th>Pres sub eu</th>
    <th>Pres sub ele</th>
    <th>Pres sub nos</th>
    <th>Pres sub eles</th>
    <th>Imp sub eu</th>
    <th>Imp sub ele</th>
    <th>Imp sub nos</th>
    <th>Imp sub eles</th>
    <th>Fut sub eu</th>
    <th>Fut sub ele</th>
    <th>Fut sub nos</th>
    <th>Fut sub eles</th>
    <th>Sent1</th>
    <th>Sent2</th>
    <th>Sent3</th>
    <th>Sent4</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @verbs.each do |verb| %>
      <tr>
        <td><%= verb.entry_id %></td>
        <td><%= verb.verb %></td>
        <td><%= verb.definition %></td>
        <td><%= verb.gerundio %></td>
        <td><%= verb.participio %></td>
        <td><%= verb.pres_eu %></td>
        <td><%= verb.pres_ele %></td>
        <td><%= verb.pres_nos %></td>
        <td><%= verb.pres_eles %></td>
        <td><%= verb.pret_eu %></td>
        <td><%= verb.pret_ele %></td>
        <td><%= verb.pret_nos %></td>
        <td><%= verb.pret_eles %></td>
        <td><%= verb.imp_eu %></td>
        <td><%= verb.imp_ele %></td>
        <td><%= verb.imp_nos %></td>
        <td><%= verb.imp_eles %></td>
        <td><%= verb.fut_eu %></td>
        <td><%= verb.fut_ele %></td>
        <td><%= verb.fut_nos %></td>
        <td><%= verb.fut_eles %></td>
        <td><%= verb.cond_eu %></td>
        <td><%= verb.cond_ele %></td>
        <td><%= verb.cond_nos %></td>
        <td><%= verb.cond_eles %></td>
        <td><%= verb.pres_sub_eu %></td>
        <td><%= verb.pres_sub_ele %></td>
        <td><%= verb.pres_sub_nos %></td>
        <td><%= verb.pres_sub_eles %></td>
        <td><%= verb.imp_sub_eu %></td>
        <td><%= verb.imp_sub_ele %></td>
        <td><%= verb.imp_sub_nos %></td>
        <td><%= verb.imp_sub_eles %></td>
        <td><%= verb.fut_sub_eu %></td>
        <td><%= verb.fut_sub_ele %></td>
        <td><%= verb.fut_sub_nos %></td>
        <td><%= verb.fut_sub_eles %></td>
        <td><%= verb.sent1 %></td>
        <td><%= verb.sent2 %></td>
        <td><%= verb.sent3 %></td>
        <td><%= verb.sent4 %></td>
        <td><%= link_to 'Show', verb %></td>
        <td><%= link_to 'Edit', edit_verb_path(verb) %></td>
        <td><%= link_to 'Destroy', verb, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Verb', new_verb_path %>

app/views/irregularverbs/new.html.erb
<h1>New verb</h1>

<%= render 'form' %>

<%= link_to 'Back', verbs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Verbapp</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= yield %>
</body>

</html>

app/views/verbs/index.html.erb
<h1>Listing verbs</h1>

<table>
  <tr>
    <th>Entry</th>
    <th>Verb</th>
    <th>Definition</th>
    <th>Participio</th>
    <th>Gerundio</th>
    <th>Pres eu</th>
    <th>Pres ele</th>
    <th>Pres nos</th>
    <th>Pres eles</th>
    <th>Pret eu</th>
    <th>Pret ele</th>
    <th>Pret nos</th>
    <th>Pret eles</th>
    <th>Imp eu</th>
    <th>Imp ele</th>
    <th>Imp nos</th>
    <th>Imp eles</th>
    <th>Fut eu</th>
    <th>Fut ele</th>
    <th>Fut nos</th>
    <th>Fut eles</th>
    <th>Cond eu</th>
    <th>Cond ele</th>
    <th>Cond nos</th>
    <th>Cond eles</th>
    <th>Pres sub eu</th>
    <th>Pres sub ele</th>
    <th>Pres sub nos</th>
    <th>Pres sub eles</th>
    <th>Imp sub eu</th>
    <th>Imp sub ele</th>
    <th>Imp sub nos</th>
    <th>Imp sub eles</th>
    <th>Fut sub eu</th>
    <th>Fut sub ele</th>
    <th>Fut sub nos</th>
    <th>Fut sub eles</th>
    <th>Sent1</th>
    <th>Sent2</th>
    <th>Sent3</th>
    <th>Sent4</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @verbs.each do |verb| %>
      <tr>
        <td><%= verb.entry_id %></td>
        <td><%= verb.verb %></td>
        <td><%= verb.definition %></td>
        <td><%= verb.participio %></td>
        <td><%= verb.gerundio %></td>
        <td><%= verb.pres_eu %></td>
        <td><%= verb.pres_ele %></td>
        <td><%= verb.pres_nos %></td>
        <td><%= verb.pres_eles %></td>
        <td><%= verb.pret_eu %></td>
        <td><%= verb.pret_ele %></td>
        <td><%= verb.pret_nos %></td>
        <td><%= verb.pret_eles %></td>
        <td><%= verb.imp_eu %></td>
        <td><%= verb.imp_ele %></td>
        <td><%= verb.imp_nos %></td>
        <td><%= verb.imp_eles %></td>
        <td><%= verb.fut_eu %></td>
        <td><%= verb.fut_ele %></td>
        <td><%= verb.fut_nos %></td>
        <td><%= verb.fut_eles %></td>
        <td><%= verb.cond_eu %></td>
        <td><%= verb.cond_ele %></td>
        <td><%= verb.cond_nos %></td>
        <td><%= verb.cond_eles %></td>
        <td><%= verb.pres_sub_eu %></td>
        <td><%= verb.pres_sub_ele %></td>
        <td><%= verb.pres_sub_nos %></td>
        <td><%= verb.pres_sub_eles %></td>
        <td><%= verb.imp_sub_eu %></td>
        <td><%= verb.imp_sub_ele %></td>
        <td><%= verb.imp_sub_nos %></td>
        <td><%= verb.imp_sub_eles %></td>
        <td><%= verb.fut_sub_eu %></td>
        <td><%= verb.fut_sub_ele %></td>
        <td><%= verb.fut_sub_nos %></td>
        <td><%= verb.fut_sub_eles %></td>
        <td><%= verb.sent1 %></td>
        <td><%= verb.sent2 %></td>
        <td><%= verb.sent3 %></td>
        <td><%= verb.sent4 %></td>
        <td><%= link_to 'Show', verb %></td>
        <td><%= link_to 'Edit', edit_verb_path(verb) %></td>
        <td><%= link_to 'Destroy', verb, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Verb', new_verb_path %>